[package]
name = "asp"
version = "0.1.0"
edition = "2024"

[dependencies]
cdcl = { path = "../cdcl" }
relational = { path = "../relational" }
contiguous_data = { path = "../contiguous_data" }
serde = { version = "*", features = ["derive"] }
serde_json = "*"

[[bin]]
name = "asp"
path = "src/main.rs"
