[package]
name = "cdcl"
edition.workspace = true
version.workspace = true

[features]
dhat-heap = ["dep:dhat"]

[dependencies]
ahash = { workspace = true }
anyhow = "*"
clap = { version = "*", features = ["derive"] }
consume_on_drop = "*"
contiguous_data = { path = "../contiguous_data" }
ctrlc = "*"
dhat = { version = "*", optional = true }
either = "*"
frunk = "*"
frunk_core = "*"
frunk_utils = "*"
frunk_utils_derives = "*"
priority-queue = "*"
rand_chacha = "*"
relational = { path = "../relational" }
