[package]
name = "relational"
edition.workspace = true
version.workspace = true

[features]
consolidate_all = []

[dependencies]
ahash = { workspace = true }
anyhow = "*"
arrayvec = "*"
contiguous_data = { path = "../contiguous_data" }
derive-where = "*"
either = "*"

[dev-dependencies]
proptest = "*"
